[package]
name = "extrem_scene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Scene components and helpers for ExtremEngine"

[dependencies]
extrem_ecs = { path = "../extrem_ecs" }
extrem_math = { path = "../extrem_math" }

[lints]
workspace = true
