[package]
name = "extrem_mesh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Mesh types and vertex layouts for ExtremEngine"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
extrem_math = { path = "../extrem_math" }
extrem_ecs = { path = "../extrem_ecs" }

[lints]
workspace = true
